wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.16.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1701144609.628769
    t:
      1:
      - 55
      - 105
      2:
      - 55
      - 105
      3:
      - 2
      - 23
      4: 3.11.4
      5: 0.16.0
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
